### ISSUE TITLE
convert symbol/base/quote fiat

### ISSUE THREAD

**Issue by slicken** [kroitor/ccxt#105]
hi.
first I would like to say, thx for sharing this amazing API!

my question is, if there a easy way to convert a symbol base or quote currency to usd or eur or any other fiat.
this would help to be able to set a minimum / maximum trade sizes in USD for example.

**Comment by kroitor** [comment]
Hi! Thanks for your feedback )

> my question is, if there a easy way to convert a symbol base or quote currency to usd or eur or any other fiat.

Well... my answer would be: yes, there is a way, you can use the ccxt library for that ) Though you will have to calculate your rates manually, the library provides you with all means for that. The library cannot define the logic of conversion rates, we can only automate it in a very non-intrusive way.

For that, we plan to add methods for getting volumetric order book prices, but, in the meantime, you can convert manually, depending on which rates (from which exchanges) you want to use. These methods will help in rate conversions. They will account for volume and will give you a true weighed price for a certain volume in the order book.

You see, there's ambiguity in currency pair rates, because each exchange has its own rates, and there are so many crypto and forex exchanges out there... you cannot physically account for all of them to get a true weighed price. Moreover, not all exchanges support USD or fiat at all. 

So, in order to get desired conversion rates you need to specify the exchanges you want to *weigh* and currencies you want to *weigh in*. There's no general way of doing it such that would satisfy all users. We can only automate it a little bit. Or I may be not getting the question in full entirety here, if that is the case, please explain.

To convert manually, you just get the rates by fetching the order book, calculate the price for your desired volume and then you basically multiply to get the true price (on one specific exchange).

**Comment by slicken** [comment]
Thanks for quick answear.
For example. I have specified min_trader_size = 50  # EUR
Now when im looking to automate a trade on Gdax or Kraken that have EUR this would work with exact rates.
But as Bittrex or most other brokers dont have EUR it would be hard to calculate the tradesize so its below my min_trade_size that is set in EUR.

I found a quick dirty way to grab convertations like (python):

```
symbol = 'LTC/USD'
base = re.all('^\w+', symbol)
quote= re.all(^\w+$, symbol)
url = 'https://api.cryptonator.com/api/ticker/{0}-{1}'.format(base.lower(), quote.lower())
request = _urllib.Request(url)#, body, headers)
handler = _urllib.HTTPHandler if url.startswith('http://') else _urllib.HTTPSHandler
opener = _urllib.build_opener(handler)
response = opener.open(request, timeout = 100)
text = response.read()
print(text)

```
But now when I think about it, i better set limitations in BTC as most brokers have it and the rate would be 100% accurate to its broker.

**Comment by kroitor** [comment]
> For example. I have specified min_trader_size = 50 # EUR

This is actually beyond the scope of the library, because this relates to your applied strategy, or the bot you're trying to write logic for.

> Now when im looking to automate a trade on Gdax or Kraken that have EUR this would work with exact rates. But as Bittrex or most other brokers dont have EUR it would be hard to calculate the tradesize so its below my min_trade_size that is set in EUR.

Your code snippet will not give you fair rates. 

First, it's another intermediary (cryptonator) that adds lag and latency, so if you grab prices from an indirect intermediary (and not from the exchange  directly, first-hand), then you're not guaranteed that your orders will be even close to your desired prices, because order books can change significantly in a fraction of a second. Each added intermediary will contribute to your lag.

Second, you are receiving the top bid/ask prices from ticker API, and that is not correct if you want true price. You should get the full order book and calculate accumulated prices from the order book for your exact volume if you really want true conversion rates.

If I answered your questions, please close this issue, and if not, I'll be happy to answer your further questions.

**Comment by slicken** [comment]
thanks for response. yes, it helped !
i think trade_size in btc will be best, as i can calculate real rate from specific exchanges orderbook . Thanks!
