### ISSUE TITLE
Add market url

### ISSUE THREAD

**Issue by thijstriemstra** [kroitor/ccxt#108]
Would be nice to have a way to get the market website url, e.g. https://bittrex.com/Market/Index?MarketName=BTC-NEO. Or is this already available?

**Comment by kroitor** [comment]
I will do that if you can define 'market url' for all exchanges ) I mean, not all of them even have an url for fetching markets...

**Comment by thijstriemstra** [comment]
Can you tell me where I would add this field? In some js file that gets transpiled?

**Comment by kroitor** [comment]
Do you think adding web urls to pages of their websites except for the homepage and docs is really needed inside the library? Is that feature of having the web URLs necessary to or wanted by all users in terms of library scope?

I mean, those URLs can change because an exchange usually does a website redesign more frequently than it introduces API changes, and keeping all that consistent will be a big pain to me (and you also, probably).

URLs are defined in the beginning of each class in ccxt.js (as is in ccxt/__init__.py the syntax is JSON-like, single-quoted keys, ints, arrays and strings, spaces around brackets ;))

You will have to define such a templated URL like: `http://www.somexchange.com/Path/To/Market/Page/If/It/Exists/At/All/And/What/You/Gonna/Do/If/Not` and then for each exchange to define a method that passes the market id to a call to the internal `request ()` method (which is also defined for all markets).

That request method does one of the following:
1. If params should be imploded in the URL: it implodes the passed `params` dict into the URL-path, such that, if the URL template is `/abc/{def}/{ghi}` and `params = { 'def': 'foobar', 'ghi': 'barfoo' }`, after imploding params the URL is `/abc/foobar/barfoo`.
2. If params should be passed in the query string - it urlencodes them and concatenates with the url with '?' in the middle.
3. If an URL requires both, it does both 1 and 2.

After that, the `request ()` method performs the request, so you would need to decouple the url-generation from the `request ()` method and do it consistently for all exchanges.

**Comment by kroitor** [comment]
In particular, the list of methods for URL substitutions in Python is:

```Python
self.implodeParams(path, params) # implodes params dict into path
self.omit(dict, keys) # omits listed keys from dict
self.extractParams(path) # returns a list of {keys} from path
self.urlencode(params) # self-explaining
```

**Comment by kroitor** [comment]
```Python
url = 'https://bittrex.com/Market/Index?MarketName={id}'
print(bittrex.implodeParams ({ 'id': bittrex.products['ETH/BTC']['id'] }))
url2 = 'https://otherexchange.com/{id}/TradeOrSomething'
print (otherexchange.implodeParams (...))
url3 = 'https://adifferentexchange.com'
print (url3 + '?' + adifferentexchange.urlencode ({ 'the_param_name': adifferentexchange.products['ETH/BTC']['id'] })
```

**Comment by kroitor** [comment]
@thijstriemstra what do you think of the above?

**Comment by thijstriemstra** [comment]
Sounds good.

**Comment by kroitor** [comment]
@thijstriemstra ok, I will do this for bittrex and then you can follow up. Will let you know.

**Comment by kroitor** [comment]
Ok, I did the example implementation of getMarketURL/get_market_url  for bittrex and poloniex, there are two different ways of injecting a market id:

1. as URL query params (bittrex, lines 3526-3532 in ccxt.js → lines 3468-3473 in ccxt/__init__.py)
2. into the URL path (poloniex, lines 11761-11767 in ccxt.js → 11360-11365 in ccxt/__init__.py)

If you can go on and do the similar thing for all other markets – I will merge it very quickly (even if there are conflicts or bugs). You only need to do the js part, everything else should be transpiled normally. If you have difficulties with it, go ahead and do it in Python, I will port it to other languages.

Available in v.1.3.80.

Thanks!

**Comment by kroitor** [comment]
Also, added a `exchange.urls['market']` property, see bittrex and poloniex defaults in the beginning of each of the two derived classes in JS and Python.

**Comment by kroitor** [comment]
Hi, @thijstriemstra! I'm sorry, I don't really have enough time for all of the pending tasks (have to work on async/websocket APIs), can you do the getMarketURL/get_market_url implementations for URLs added in #112 yourself ? I will then merge it, when you're done, if that's ok to you.

**Comment by kroitor** [comment]
P.S. I don't really think adding these URLs is a good idea – it's beyond the scope of the library. Still in doubt about this.
