### ISSUE TITLE
Support Binance exchange

### ISSUE THREAD

**Issue by wtksyjpy** [kroitor/ccxt#142]
Could you please help add support for Binance exchange?
https://www.binance.com/restapipub.html
Thank you so much!!

**Comment by kroitor** [comment]
We will add it in a couple of days probably! Thx!

**Comment by wtksyjpy** [comment]
Thank you so much!! :-)

**Comment by kroitor** [comment]
Ok, we have added support for Binance in version 1.4.92+. Please feel free to ask questions, we will be very thankful for your feedback! In the meantime I'm closing this issue, and if you have any problems or it does not work for you, let us know so that we could fix it for you. As far as we have tested it, the exchange should be working normally in all languages. Thx!
