### ISSUE TITLE
Suggestion: Convert any pair to USD

### ISSUE THREAD

**Issue by a-marionette** [kroitor/ccxt#158]
Hi,

I am not sure if this functionality is implemented, but is there any built-in functionality that can convert a pair to its USD value? For example, https://www.worldcoinindex.com/coin/ethereum will display a USD conversion of all pairs (if selected from the dropdown).

- ETH/BTC to USD
- LTC/CNY to USD

**Comment by kroitor** [comment]
Sure! That built-in functionality is called the ccxt library ;)) That's the short answer )

If you want a longer one, then, please, elaborate, how would you convert DASH/BTC to USD on Kraken (a US exchange)? And then, how would you convert BCH/JPY to USD on Zaif (a Japanese exchange)?

**Comment by kroitor** [comment]
Before you answer, you should also remember, that we are developing a library, therefore we have to convert to any currency from any currency in such a way that would satisfy everyone (read: not only you). So, if you choose to convert to USD, why not converting to ETH, or to JPY, or to EUR in the first place?

**Comment by kroitor** [comment]
I am closing this for now because converting from all currencies to all currencies is beyond the scope of the ccxt library, that functionality is to be layered on top of it by the user himself.

ccxt is a low-level library. Price conversion is what it is designed to be used for, but it will not convert everything for you (you will have to do that yourself and ccxt can help you with that). 

It isn't an all-in-one framework, but more like a building block for your application and business logic. It really depends on how a user wants to calculate their conversion rates and there's no general way to do that, afaik. We intend to keep the library light and as simple as possible.

Thx for your feedback anyway!
