### ISSUE TITLE
Decoupling python/php code from transpiler

### ISSUE THREAD

**Issue by nmiculinic** [kroitor/ccxt#17]
I'd like contributing to python codebase, however, am unable to since it's heavily coupled with js one, without good reason. 

Most APIs differ by URL endpoints and regex substitution for pairs. I suggest having API definition folder, for example /API_def/kraken.json where API specific configuration is provided. Market than would load this file and know everything needed to perform its unified API duties. 

Most APIs have json responses, thus JSON path can be configured in the configuration file. For example let's take kraken ticker for example:
```json
"kraken":{
    "ticker":{
        "api_endpoint": "https://api.kraken.com/0/public/Ticker/{pair_name}",
        "last": "{pair_name}.c[0]"
        ...
    }
}
```

Since you've spent more time looking at API configuration you're more familiar what's needed.  {pair_name} and other serve as substitution points in the API. How does this look to you?

**Comment by kroitor** [comment]
> I'd like contributing to python codebase, however, am unable to since it's heavily coupled with js one, without good reason.

We welcome you to open pull requests and issues and we really appreciate your help!

There is a reason for coupling, though: we are developing a single codebase which is much easier to maintain than multiple codebases. I would say, Python-version is not coupled with JS, but is generated from JS by more than 95% (as is PHP), including not only the schemas, but all unified methods also. The only thing that's not common is the base Market class, everything else is a result of our custom hand-made transpilation scripts.

> Most APIs differ by URL endpoints and regex substitution for pairs.

Endpoint schema is not the only thing that differs from market to market. The generic request method and all other unified methods also have specific implementations and are also transpiled from JS. This is why having only the URL schema separated is not sufficient to do the job, we would have to separate the code as well. I would say, only 50% of supported exchanges can be reduced to a common schema with moderate pain.

By the way, I'm not using regexes inside the unified API, because they may differ in syntax and modifiers very much. I'm only using them in the base class. As for urlpath vars, they are imploded into the URL by basic substring replacement.

> I suggest having API definition folder, for example /API_def/kraken.json where API specific configuration is provided. Market than would load this file and know everything needed to perform its unified API duties.

There are two points for having the whole thing in a single source file:
- The ccxt library offers a web-version (in JS) for browsers, for developing web-/mobile-apps that communicate with exchanges. This is the reason to avoid disk access inside the library at all costs. This is why having all files separated would make the library hard to link against, in some environments.
- Also, a significant time will be wasted for switching between contexts of work. When you are dealing with several files, it's ok, but when you have to work with tens and hundreds of exchanges, it's an overkill. It may not seem to be a problem at first, but in the long term (say, a year) that wasted time sums up to hours and days just for navigating among separate files. I would rather spend that time developing the functionality ) Did you know that an average person spends several days on blinking accumulated throughout a lifetime? ) This is the same as having your eyes closed for a long continuous period ) I would rather not blink at all if I could, I miss that wasted time very much )

> Most APIs have json responses, thus JSON path can be configured in the configuration file.

Yes, but that's only true for parsing a basic response, like a ticker. There are some cases, which are not easily-defineable in a schema. Such a schema definition would have to be extremely flexible. It might even require inventing/integrating a separate language to define the schema in its entirety, or taking an existing well-developed schema parser. After all, this would need a much longer spec/syntax and a much more complex architecture. Making a flexible schema format to support all possible definitions for those special cases would bloat the codebase even more. 

> For example let's take kraken ticker for example:
> ```
> "kraken":{
>     "ticker":{
>         "api_endpoint": "https://api.kraken.com/0/public/Ticker/{pair_name}",
>         "last": "{pair_name}.c[0]"
>         ...
>     }
> }
> ```

Parsing a ticker is actually the easiest of the tasks to separate. Tickers are trivial to parse (all fields are numbers, etc). But take this more complex example (also for kraken), that does product parsing:

```Python
    def fetch_products (self):
        products = self.publicGetAssetPairs ()
        keys = list (products['result'].keys ())
        result = []
        for p in range (0, len (keys)):
            id = keys[p]
            product = products['result'][id]
            base = product['base']
            quote = product['quote']
            if (base[0] == 'X') or (base[0] == 'Z'):
                base = base[1:]
            if (quote[0] == 'X') or (quote[0] == 'Z'):
                quote = quote[1:]
            base = self.commonCurrencyCode (base)
            quote = self.commonCurrencyCode (quote)
            darkpool = id.find ('.d') >= 0 
            symbol = product['altname'] if darkpool else (base + '/' + quote) # special case 
            result.append ({
                'id': id,
                'symbol': symbol,
                'base': base,
                'quote': quote,
                'info': product,
            })
        return result
``` 

This whole method is generated from JS → Python/PHP. I don't see an easy way to schematize all those comparisons, conversions, character stripping and string splitting, 'ifs' and the 'darkpool' case without bloating the schema to an unmaintainable level of complexity. So separating this into a schema would require the schematics to be very flexible, that is much longer in syntax and is actually harder to maintain in practice. 

Now compare the previous piece of code to the same method for _1broker:

```Python
    def fetch_products (self):
        categories = self.fetchCategories ()
        result = []
        for c in range (0, len (categories)):
            category = categories[c]
            products = self.privateGetMarketList ({ # Multiple requests here
                'category': category.lower (), # they want me to lowercase their own string :\
            })
            for p in range (0, len (products['response'])):
                product = products['response'][p]
                if (category == 'FOREX') or (category == 'CRYPTO'): # A special case
                    id = product['symbol']
                    symbol = product['name']
                    base, quote = symbol.split ('/')
                    result.append ({
                        'id': id,
                        'symbol': symbol,
                        'base': base,
                        'quote': quote,
                        'info': product,
                    })
                else:
                    id = product['symbol']
                    symbol = product['symbol']
                    name = product['name']
                    type = product['type'].lower ()
                    result.append ({
                        'id': id,
                        'symbol': symbol,
                        'name': name,
                        'type': type,
                        'info': product,
                    })
        return result
```

I don't really see too much in common between these two methods, apart from the fact that some variables have identical names. This is one example of hundreds of such special cases.

> Since you've spent more time looking at API configuration you're more familiar what's needed. 

Exactly, this is how I know that schema separation is not enough. In fact, initial versions of the library had multiple separated schemas, like you suggested, but then we merged everything into a single file. It may seem like an inconvenience to you, but in the end, we think the pros for single-module overweight the cons. 

> How does this look to you?

At first glance this may sound easy to do, like, there's no big deal in having everything in a dotpath-schema, but in practice this is not easy at all, for sure (we tried that already). If you account not only for tickers/orderbooks, but all methods in general, you'll find the task quite complicated. Such a schema would also have to support some logic for parsing, variable types specs and conversions (for both input and output), etc. 

Separating the endpoints list is easy, but designing a universal set of methods sufficient to handle all endpoints/exchanges - that is hard. We will need to consider this very carefully. Yet I'm sure we'll try to handle this issue somehow, so that you could also take part in the development process.

**Comment by nmiculinic** [comment]
Yeah, you're right. Any DSL will become badly designed language in its own right since exchanges differ in simple, yet nontrivial ways. Close? Unless somebody thinks of some smart solution

**Comment by kroitor** [comment]
I think like I am closing it, but I will still try to reduce the codebase. Thanks for your involvement!
