### ISSUE TITLE
Missing some of BTCChina markets

### ISSUE THREAD

**Issue by 86chenjie** [kroitor/ccxt#175]
currently btcchina only return 3 markets: btccny/ltccny/ltcbtc
but there are other few markets to return:
https://www.btcchina.com/apidocs/plus-market-data-rest-api-zh.html
like ETH/BCC https://plus-api.btcchina.com/market/orderbook?symbol=ETHCNY&limit=5

**Comment by kroitor** [comment]
Hi!
We will add ETH markets to BTCChina, but, we would like to have a full list of supported pairs, do you know where we can get it? Can't find it anywhere there, may be due to my bad language skills. If you can help us with listing all missing pairs with BTCChina, it will help us a lot. Thx!

**Comment by 86chenjie** [comment]
https://plus-api.btcchina.com/market/orderbook?symbol=ETHCNY&limit=5
this is a example api in https://www.btcchina.com/apidocs/plus-market-data-rest-api-zh.html.
but it don't support ?symbol=all parameter.
but it support ETHCNY & BCCCNY.
https://plus.btcchina.com/ this is the list of markets.

**Comment by kroitor** [comment]
Ok, we have added missing markets (available in 1.6.52+), but there are some caveats:

1. When we ask BTCChina for all tickers (symbol=all), they don't return BCH and ETH tickers, and there's no endpoint nor a page on their site to get full list of all possible markets, therefore we had to hardcode it for BTCChina, until they make a more advanced API...

2. We substitute BCC for BCH, because BCC is often confused with Bitcoin, as written in #83
