### ISSUE TITLE
BUG: Bitfinex Not enough balance error

### ISSUE THREAD

**Issue by g666nz** [kroitor/ccxt#179]
Hi again,
So when i place an order that exceeds my balance with Hitbtc, the rejection is handled properly, but with bitfinex i receive the error in the image below, which causes my app to glitch. I have a work around it, but i wanted to know, if this is a problem from there side/my side/or ccxt's side. 

![ccxt2](https://user-images.githubusercontent.com/11820270/30176835-616eab22-9421-11e7-8419-84d468659e73.png)

**Comment by kroitor** [comment]
It's just we don't have a special handling for low balance with bitfinex. You should also catch all ExchangeError/ExchangeNotAvailable exceptions, but we will add the handling of InsufficientBalance to bitfinex and to other exchanges asap (it's a work in progress). With bitfinex I'll add it now, and with the rest of exchanges we will be adding that one by one...

**Comment by kroitor** [comment]
Ok, we've added InsufficientFunds handling to bitfinex should be working normally now. There may be other exchanges with the same symptoms though, we would be glad if you report, so that we could add appropriate handling where needed. We are doing this in parallel, but we don't have it done for all exchanges yet.

**Comment by g666nz** [comment]
As always thank you for your time.
