### ISSUE TITLE
Cryptopia Error: Nonce has already been used for this request.

### ISSUE THREAD

**Issue by thornycrackers** [kroitor/ccxt#193]
Docker Container (ubuntu:16.04)
Python 3.5.2
ccxt 1.6.95

I'm running into an error about 3/5 times I run the following script:

```
import ccxt

exchange = ccxt.cryptopia({
    'apiKey': 'mykey',
    'secret': 'mysecret',
})

exchange.fetch_balance()
exchange.fetch_open_orders('PIVX/BTC')
```

Sometimes it will execute with no errors but sometimes I will get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/ccxt/exchange.py", line 279, in handle_response
    return json.loads(body)
  File "/usr/lib/python3.5/json/__init__.py", line 315, in loads
    s, 0)
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    exchange.fetch_open_orders('PIVX/BTC')
  File "/usr/local/lib/python3.5/dist-packages/ccxt/exchanges.py", line 8387, in fetch_open_orders
    }, params)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/exchanges.py", line 8428, in request
    response = self.fetch(url, method, headers, body)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/exchange.py", line 273, in fetch
    return self.handle_response(url, method, headers, body)
  File "/usr/local/lib/python3.5/dist-packages/ccxt/exchange.py", line 295, in handle_response
    raise ExchangeError(' '.join([self.id, method, url, body, str(e)]))
ccxt.errors.ExchangeError: cryptopia POST https://www.cryptopia.co.nz/api/GetOpenOrders {"Success":false,"Error":"Nonce has already been used for this request."} Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
```

Please let me know if you need anymore information on my end.

**Comment by kroitor** [comment]
@thornycrackers hi!

This is because you are hitting the request limit and you should redefine the Nonce if you're going to do multiple private requests one by one in less than one second.

Here, you call private methods twice a second without waiting:
```
exchange.fetch_balance()
time.sleep (exchange.rateLimit) # missing delay between consequent private requests
exchange.fetch_open_orders('PIVX/BTC')
```

If you don't want to sleep between your requests, you can override your nonce, more info on this can be found here:

https://github.com/kroitor/ccxt/wiki/Manual#rate-limit
https://github.com/kroitor/ccxt/wiki/Manual#authentication
https://github.com/kroitor/ccxt/wiki/Manual#overriding-the-nonce

The easiest way to solve your problem is to redefine your Nonce, though you may hit the rateLimit with your keypair, if you do your requests too frequently...

If you still have questions on that, I'll be happy to answer. In the meantime, I am closing this issue as a duplicate, if you don't mind. Feel free to reopen it, if needed.

**Comment by kroitor** [comment]
These symptoms are also covered in the [Troubleshooting](https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting) section. Let us know if this does not help you.

**Comment by rokcarl** [comment]
Yep, I solved it like this when I initialize the exchange:
```
ccxt.cryptopia({'nonce': lambda: ccxt.Exchange.milliseconds()})
```

Actually, I have a general purpose method to initialize an exchange inside one of my classes:

```
  def __init__(self, name, slug, key, secret):
    self.key = key
    self.secret = secret
    self.name = name
    self._markets_loaded = False

    if slug == "cryptopia":  # cryptopia needs the nonce overwrite
      self.api = getattr(ccxt, slug)({'nonce': lambda: ccxt.Exchange.milliseconds()})
    else:
      self.api = getattr(ccxt, slug)()
    self.api.apiKey = key
    self.api.secret = secret
```

**Comment by kroitor** [comment]
@rokcarl thanks for posting it!
