### ISSUE TITLE
BTCChina BCH TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by 86chenjie** [kroitor/ccxt#194]
Cannot convert undefined or null to object

**Comment by kroitor** [comment]
Thx! I'll take a look and fix this asap!

**Comment by kroitor** [comment]
The problem is your previous issue #175 that requested to add those markets to btcchina.

The reason for not adding those markets initially was because they have problems with serving some of them...

```
https://data.btcchina.com/data/orderbook?market=bcccny
https://data.btcchina.com/data/orderbook?market=bchcny 
https://data.btcc.com/data/orderbook?market=bcccny
https://data.btcc.com/data/orderbook?market=bchcny
```

All of these URLs return an empty array `[]` (you can see that by turning on verbose mode).
So, it's a problem on their side, I suppose, and this is why I didn't add those markets to btcchina in the first place... 

What should I do about it? I'm a little confused... Either remove those markets, or just always return an empty orderbook? I don't really think you will like empty orderbooks ))

Next, the tickers:

```shell
https://data.btcchina.com/data/ticker?market=btccny # ok
https://data.btcchina.com/data/ticker?market=bchcny # fail
https://data.btcchina.com/data/ticker?market=bcccny # fail
```

As you can see, none of BCH or BCC work at all there...

I will investigate further into it...

**Comment by 86chenjie** [comment]
https://plus-api.btcchina.com/market/ticker?symbol=ETHCNY
they have different urls for eth & bcc.

**Comment by kroitor** [comment]
@86chenjie awesome, then we can work it out ) Thx a lot, I'll fix it and I hope upload the working version asap.

**Comment by kroitor** [comment]
Ok, this is fixed in version 1.6.98+. It works now ) Please update and test it on your side. As always, we will be happy if you report back. Thx!

**Comment by 86chenjie** [comment]
test BCH & ETH. both work fine.  👍

**Comment by kroitor** [comment]
We appreciate your feedback a lot!
