### ISSUE TITLE
Bitstamp missing altcoin withdrawal methods

### ISSUE THREAD

**Issue by marinsokol5** [kroitor/ccxt#198]
Using `ccxt-1.6.103`.

`Bitstamp`'s params in init (the ones defining requests).
In private API there should be methods for fetching adress and doing withdrawal.
There seems to be Ripley(XRP) but not the other currencies.
```
private 
         post 
               'xrp_address/',
               'xrp_withdrawal/',
```

Requests missing:
Private post 
```
https://www.bitstamp.net/api/v2/ltc_address/
https://www.bitstamp.net/api/v2/ltc_withdrawal/
https://www.bitstamp.net/api/v2/eth_withdrawal/
https://www.bitstamp.net/api/v2/eth_address/
https://www.bitstamp.net/api/bitcoin_deposit_address/
https://www.bitstamp.net/api/unconfirmed_btc/
https://www.bitstamp.net/api/bitcoin_withdrawal/
```

I know that bitcoin is v1 version of API but do you think it could be squized in?
Maybe they have something like `btc_address` and `btc_withdrawal` but they forgotted to put it.
:)

**Comment by kroitor** [comment]
I'll take a look. We will either implement those methods in bitstamp v1, or we will add support for v2. Thx for this proposal, we hope to deliver very soon!

**Comment by kroitor** [comment]
Ok, we have added missing endpoints to Bitstamp v2, and we have also added an implementation of Bitstamp v1, just in case it's needed... We don't have all withdrawal methods implemented and unified (yet, hehe ;) but you have the full set of endpoints at least. 

This issue should be fixed in v1.6.109+, which will be available for downloading in a few minutes.
We will be happy if you update and help us test it. Please, report back if you find any errors, bugs or something...

As always, thanks for your participation! We will update you on the progress of withdrawal unification.

**Comment by Iorek69** [comment]
Hi, has this issue been resolved? I don't see it in ccxt.bitstamp or ccxt.bitstamp1. Good work on this whole library, 10/10 effort

**Comment by kroitor** [comment]
> Hi, has this issue been resolved?

Yes.

> I don't see it in ccxt.bitstamp or ccxt.bitstamp1. Good work on this whole library, 10/10 effort

You don't see them, because those methods get generated upon instantiation. To see them, do this:

```JavaScript
Object.keys (new ccxt.bitstamp ())
      .filter (key => typeof exchange[key] == 'function')
      .map (key => console.log (key))
```

```Python
print(dir(ccxt.bitstamp()))
```

**Comment by Iorek69** [comment]
That makes sense. Thank you very much, and again, thanks for the library!
