### ISSUE TITLE
Bittrex accountGetOrderhistory is not parsed

### ISSUE THREAD

**Issue by bernatfortet** [kroitor/ccxt#202]
Looking at the source code I see that you are parsing the order History. 

But in my code I can only fetch the unparsed response from bittrex.
```js
async function fetchTrades(){
  const bittrex = new ccxt.bittrex({
    'apiKey': xxxx,
    'secret': xxxx,
  })

  return await bittrex.accountGetOrderhistory()
```
How do I access to the parsed response?

Thanks

**Comment by bernatfortet** [comment]
After reading the manual I found that there's 2 sets of methods. Exchange Api and Unified Api.
Thanks for writing it all down and sorry for asking before deep diving into the manual.

**Comment by kroitor** [comment]
Hi! No problem, thanks for reporting back anyaway! We're glad you have it resolved )

**Comment by bernatfortet** [comment]
Well, you guys must know all the apis from start to end.
I'm trying to find an api that gives me as many tickers as possible.
CoinMarketCap only provide BTC-XXX pairs. While there's also ETH-XXX, LTC-XXX in some exchanges.

Do you think CoinMarketCap is the most comprehensive one?

Thanks!

**Comment by kroitor** [comment]
@bernatfortet it depends on what your goals are... Traders are very selective and are not interested in getting "any" information from "any" source by "any" means... 

The information is often needed as quickly as possible, and the quickest way is to get it – is to take fetch it from the exchange directly. 

CoinMarketCap is not an exchange. It is what is called a *data aggregator*. Coinmarketcap obtains data from the exchanges for you. So, your data could travel different pathways:

1. exchange → you
2. exchange → coinmarketcap → you

As you can see, coinmarketcap is just an intermediary that adds round-trip time and latency to your data. So, it really depends on why you need the data.

If you just want to have it for later use no matter how fresh it is and no matter how long it took to obtain it – you can use cmc to get it. But if you want to trade, be very quick, reactive and competitive, you would rather prefer to work with particular exchanges directly with no unnecessary intermediaries and trade a very-well defined list of pairs available with them. 

So, traders like to choose which exchanges to trade against (with respect to fees of each exchange and other factors) and the need for "all possible tickers" is not so common... They usually want "something particular" instead of "everything just in case".

Now, if you're trying to build an system that would just gather financial info and work on it somehow, coinmarketcap can suit your purposes. But in general, if you want to distribute that information later, people will mostly be asking you how fresh the info is and through how many hands it has passed before arriving.

**Comment by bernatfortet** [comment]
@kroitor thanks for the thorough explanation.
I'll keep that in mind for my future trading side of development.
For now a data aggregator makes things simpler since I don't need high speeds. Do you know if there'a any data aggregator better than CMC?

Thanks!

**Comment by kroitor** [comment]
- https://www.coinigy.com
- https://www.cryptodashboard.com
- https://cryptrader.com
- https://coinmarketcap.com
- https://www.cryptocompare.com
- https://blog.gdax.com/announcing-the-gdax-trading-toolkit-dd4a53a1bddd
- ...
