### ISSUE TITLE
New exchange request: Independent Reserve 

### ISSUE THREAD

**Issue by sgresham** [kroitor/ccxt#209]
Hi guys,

Great platform, I spent so much time building my site figuring things out and your code has cut thousands of lines of pretty poor code :)

It would be great if you could add another Aussie exchange, independent reserve.

Site: www.independentreserve.com

API: https://www.independentreserve.com/API

Once again, thanks for the great work!!

**Comment by kroitor** [comment]
Hi! @sgresham ! Thanks for your proposal, we actually have IR implemented already, so, we will add it very soon.

**Comment by kroitor** [comment]
We have added an experimental integration of the Independent Reserve.
It will be available in version 1.7.25+.

We were only able to test their public API, because they are still verifying our account. 

Now our options are:

- We will be very happy if you would be so kind to send us a zero-balance keypair for testing (better do it by email if you agree), like other users did in their previous requests. We don't need your money nor your personal info, it's for testing purposes only.
- You can try and test the private unified methods (fetchBalance, createOrder, cancelOrder) and report back here, it would also be very helpful.

I'm closing this issue for now, if you don't mind. Feel free to reopen it, if needed.
Let us know if you have questions or if you have any difficulty with it.

Thx!

**Comment by sgresham** [comment]
Hi Kroitor,
I am testing out what I can at the moment and have found one issue so far with privateAPI signon for IndependentReserve.

it appears that 
"let message = ','.join (auth);" 
should be 
"let message = auth.join (',');"

I also had problems until I changed the nonce to milliseconds, however that may be because my previous API was using milliseconds.

I successfully receive an account balance with these changes, I am yet to test the create and cancel orders.

cheers,
Steve

**Comment by kroitor** [comment]
@sgresham thanks for reporting! I fixed the `join` issue (confused it with python syntax, where it is reversed). Also, I'll check for the nonce as well very soon.

**Comment by kroitor** [comment]
@selaromi the nonce problem is probably related to your account / API credentials, to check for that try it with a fresh new keypair. Here's what they say in their docs:

![screen shot 2017-09-18 at 06 34 24](https://user-images.githubusercontent.com/1294454/30528432-9792a34e-9c3b-11e7-8ac7-54c6fa0dc9bc.png)

**Comment by sgresham** [comment]
Thank you Sir. I can confirm the new package works as expected. Once I get a bit of time I will confirm the create and cancel functions work.

Steve

**Comment by kroitor** [comment]
Thanks for reporting back! Let us know if you have any difficulties with it. We appreciate your help!
