### ISSUE TITLE
CryptoCompare API

### ISSUE THREAD

**Issue by PolybitSol** [kroitor/ccxt#41]
Hey,

This is more a suggestion than anything, but have you considered implementing the CryptoCompare API, found [here](https://www.cryptocompare.com/api/)? 

It provides a good amount of data on the cryptomarket; including daily, hourly and minutely price data. Beyond that there's good 'coin snapshots' which also provide good stats on various products. The PriceHistorical endpoint could also allow for a good currency conversion implementation.

Thanks for taking the time to read.

**Comment by kroitor** [comment]
Hi! Thanks for your proposal! We will study their docs and implement their API, why not )

**Comment by kroitor** [comment]
Hi! 

An update on this: after a thorough investigation, we came to a conclusion, that CryptoCompare has pretty much the same list of supported exchanges as ccxt does. But we don't see a reason to link to exchanges through an intermediary, whereas with ccxt you can connect to same exchanges and trade directly (read: faster, lower round-trip times and latencies, etc...). 

So, for that particular aggregator, we don't think we're going to implement it in ccxt. Instead, we will be adding new exchanges (the ones we miss), so that you would not need CryptoCompare in the first place. Sorry if that is not what you waited for! This is not our final decision, we may return to it later. If you know a reason for why users would want indirect connections through CryptoCompare, we will be happy to know. Thx for your feedback anyway!

**Comment by JosefJezek** [comment]
@kroitor CryptoCompare has great aggregation index for comparison.

Please add CryptoCompare. We have already CoinMarketCap. ;-)

**Comment by kroitor** [comment]
@JosefJezek we will reconsider this, thx!

**Comment by payala** [comment]
I agree in general with what you've said @kroitor, but for some particular exchanges, like cryptopia, there is no support in the API to get charts.

Although ccxt does a nice workaround of building ohlcv data from trades, this usually renders very short-term data. This could possibly be a good use for cryptocompare.

**Comment by payala** [comment]
I was having a look at cryptocompare ohlcv data, and I found out that for any ohlcv data below 1h period, not more than 48h of data is given. Which is similar to what can be obtained currently with the ccxt-generated ohlcv data. 

For 1h candles there is a lot of depth given, something like 2-3 months. In any case, i couldn't find this specified anywhere, it is just an observation from a quick test of mine.

**Comment by jonchurch** [comment]
@payala Cryptocompare historic prices (OHLCV) maxes out at 7 days worth of data for resolutions below 60 minutes
