### ISSUE TITLE
Bitstamp missing pairs

### ISSUE THREAD

**Issue by davidpodrebarac** [kroitor/ccxt#48]
Hi, when loading products for bitstamp exchange I only get 6 out of 9 available pairs. The following are missing: "ltc/usd", "ltc/eur" and "ltc/btc".

**Comment by kroitor** [comment]
Hi! Thank you for reporting this! Unfortunately, the bitstamp does not have a public API for product pairs, that's why the set of pairs is hardcoded for this exchange. We will now add the Litecoin pairs (may take something from minutes to a couple of hours for testing). Thanks again! Will update you on this very soon.

**Comment by kroitor** [comment]
The LTC pairs will be available withing bitstamp in the upcoming new version release (1.1.70)

**Comment by kroitor** [comment]
The LTC is available now in version 1.1.70. Thank you!
