### ISSUE TITLE
chbtc getOrder fail

### ISSUE THREAD

**Issue by 86chenjie** [kroitor/ccxt#74]
var chbtcOrder = await chbtc.privatePostGetOrder({id: chbtcOrderId, currency: chbtc.productId(chbtcProduct)})

{ code: 1000, message: '操作成功', id: '2017073111692829' }
2017073111692829
chbtc https://trade.chbtc.com/api/getOrder?method=getOrder&accesskey=7c566473-a14e-4cc3-9e60-65d0e7b108ce&sign=cbd0a87a522846aab0d5aa821f0c3629&reqTime=1501467045897 { method: 'POST',
  headers: { 'User-Agent': 'ccxt/1.1.112 (+https://github.com/kroitor/ccxt) Node.js/7.10.0 (JavaScript)' },
  body: undefined }

from the log, id/currency not passed as query string.

apiKey: '7c566473-a14e-4cc3-9e60-65d0e7b108ce',
secret: 'daf56366-8245-4f2d-8c4f-ec99b8afbfe6',

**Comment by kroitor** [comment]
Hi there! Give me a sec, I'll take a look into it.

**Comment by kroitor** [comment]
Yep, unfortunately, it's a bug in the library due to a flaw in chbtc API – they need the order of params to be unsorted, but very precise. Because of that, if you want to use their non-unified private API, you should set your params for chbtc as a string, like so:

```JavaScript
"use strict";
let ccxt = require ('./ccxt')
let chbtc = new ccxt.chbtc ({
	apiKey: "aa149b74-f022-45b8-9794-332620f671a1",
	secret: "d7aa3120-df98-4594-8511-4e75413b8d42",
	verbose: true,
})

async function test () {

	await chbtc.loadProducts ()
	                                       //   your order id here  your product id here
	// returns "order not found" message is it should       ↓                 ↓
	console.log (await chbtc.privatePostGetOrder ('&id=' + 123 + '&currency=btc_cny'))

	// this an alternative new unified method for you
	console.log (await chbtc.fetchOrder (123, { 'currency': 'btc_cny' }))

}

test ()
```

This is a special case of CHBTC. So, to work around it, you have to stringify the params your self in the exact order as they say it in their docs, if you want to use their non-unified methods.

But the good news is: we added a unified fetchOrder (id, params) method for CHBTC exchange, so that you could continue your work with it. You can call like so:
```JavaScript
chbtc.fetchOrder (123, { 'currency': chbtc.productId (chbtcProduct) })
```

This method is now available with CHBTC since version 1.1.148.

Thanks for your feedback!

**Comment by 86chenjie** [comment]
👍

**Comment by kroitor** [comment]
If you still have questions remaining after that, just post them and we will try our best to answer. And if the above solution worked for you and the problem is gone now, please, close this issue. Thank you very much for helping us! )

**Comment by 86chenjie** [comment]
work fine! Thanks!

**Comment by kroitor** [comment]
Thanks!
