### ISSUE TITLE
Usage of changelog

### ISSUE THREAD

**Issue by thijstriemstra** [kroitor/ccxt#76]
thanks for this great library. Is it possible to keep the changelog up to date since there are so many releases? At least let us know if there are new features or backwards incompatible changes across versions.

**Comment by kroitor** [comment]
Hi! Thanks for your feedback! We will update the changelog and we'll keep it up to date )

**Comment by thijstriemstra** [comment]
cheers.

**Comment by kroitor** [comment]
Ok, we have updated it. Actually, I think we're going to automate the logging of changes, so that it will dump version numbers and improvements just in time. See the [updated changelog](https://github.com/kroitor/ccxt/blob/master/CHANGELOG.md). If you want us to add some other details to it, just list all your requirements here and we will add them. We will try to keep it up to date from now on. If you don't mind, I am closing this issue for now.

**Comment by Bomper** [comment]
Is it still possible to keep the changelog up to date, given the very frequent improvements to the library? The last update is from ~3 months ago.

**Comment by kroitor** [comment]
> Is it still possible to keep the changelog up to date, given the very frequent improvements to the library?

Need to automate it somehow, quite hard to find time for it, it's the trade off of time spent on new code vs time spent on logging the past.
